In [2]:
import pandas as pd

In [3]:
raw_data= pd.read_csv("..\data\generation_per_production_type.csv")
raw_data.head()

,Area,MTU,Biomass_Actual_Aggregated_[MW],Fossil Brown coal/Lignite - Actual Aggregated [MW],Fossil Coal-derived gas - Actual Aggregated [MW],Fossil Gas - Actual Aggregated [MW],Fossil Hard coal - Actual Aggregated [MW],Fossil Oil - Actual Aggregated [MW],Fossil Oil shale - Actual Aggregated [MW],Fossil Peat - Actual Aggregated [MW],...,Hydro Run-of-river and poundage - Actual Aggregated [MW],Hydro Water Reservoir - Actual Aggregated [MW],Marine - Actual Aggregated [MW],Nuclear - Actual Aggregated [MW],Other - Actual Aggregated [MW],Other renewable - Actual Aggregated [MW],Solar - Actual Aggregated [MW],Waste - Actual Aggregated [MW],Wind Offshore - Actual Aggregated [MW],Wind Onshore - Actual Aggregated [MW]
0,BZN|DK2,01.01.2020 00:00 - 01.01.2020 01:00 (CET),432.0,n/e,n/e,41.0,198.0,4.0,n/e,n/e,...,n/e,n/e,n/e,n/e,n/e,n/e,0.0,72.0,119.0,255.0
1,BZN|DK2,01.01.2020 01:00 - 01.01.2020 02:00 (CET),460.0,n/e,n/e,41.0,187.0,4.0,n/e,n/e,...,n/e,n/e,n/e,n/e,n/e,n/e,0.0,73.0,105.0,219.0
2,BZN|DK2,01.01.2020 02:00 - 01.01.2020 03:00 (CET),413.0,n/e,n/e,34.0,184.0,4.0,n/e,n/e,...,n/e,n/e,n/e,n/e,n/e,n/e,0.0,72.0,96.0,226.0
3,BZN|DK2,01.01.2020 03:00 - 01.01.2020 04:00 (CET),411.0,n/e,n/e,32.0,180.0,4.0,n/e,n/e,...,n/e,n/e,n/e,n/e,n/e,n/e,0.0,73.0,114.0,239.0
4,BZN|DK2,01.01.2020 04:00 - 01.01.2020 05:00 (CET),458.0,n/e,n/e,32.0,184.0,8.0,n/e,n/e,...,n/e,n/e,n/e,n/e,n/e,n/e,0.0,70.0,137.0,254.0

# Renaming Columns before putting into the Database

In [4]:
df = pd.DataFrame(raw_data)

In [5]:
df=raw_data.rename(columns={df.columns[0]: 'area',
                    df.columns[1]: 'date_hour',
                    df.columns[2]: 'biomass',
                    df.columns[3]: 'fossil_brown_coal_lignite',
                    df.columns[4] : 'fossil_coal_derived_gas',
                    df.columns[5]: 'fossil_gas',
                    df.columns[6]:'fossil_hard_coal',
                    df.columns[7]:'fossil_oil',
                    df.columns[8]:'fossil_oil_shale',
                    df.columns[9]:'fossil_peat',
                    df.columns[10]:'geothermal',
                    df.columns[11]:'hydro_pumped_storage',
                    df.columns[12]:'hydro_pumped_storage_consumption',
                    df.columns[13]:'hydro_run_river_poundage',
                    df.columns[14]:'hydro_water_reservoir',
                    df.columns[15]: 'marine',
                    df.columns[16]:'nuclear',
                    df.columns[17]:'other',
                    df.columns[18]:'other_renewable',
                    df.columns[19]:'solar',
                    df.columns[20]:'waste',
                    df.columns[21]:'wind_offshore',
                    df.columns[22]:'wind_onshore'})

In [6]:
df.head()

,area,date_hour,biomass,fossil_brown_coal_lignite,fossil_coal_derived_gas,fossil_gas,fossil_hard_coal,fossil_oil,fossil_oil_shale,fossil_peat,...,hydro_run_river_poundage,hydro_water_reservoir,marine,nuclear,other,other_renewable,solar,waste,wind_offshore,wind_onshore
0,BZN|DK2,01.01.2020 00:00 - 01.01.2020 01:00 (CET),432.0,n/e,n/e,41.0,198.0,4.0,n/e,n/e,...,n/e,n/e,n/e,n/e,n/e,n/e,0.0,72.0,119.0,255.0
1,BZN|DK2,01.01.2020 01:00 - 01.01.2020 02:00 (CET),460.0,n/e,n/e,41.0,187.0,4.0,n/e,n/e,...,n/e,n/e,n/e,n/e,n/e,n/e,0.0,73.0,105.0,219.0
2,BZN|DK2,01.01.2020 02:00 - 01.01.2020 03:00 (CET),413.0,n/e,n/e,34.0,184.0,4.0,n/e,n/e,...,n/e,n/e,n/e,n/e,n/e,n/e,0.0,72.0,96.0,226.0
3,BZN|DK2,01.01.2020 03:00 - 01.01.2020 04:00 (CET),411.0,n/e,n/e,32.0,180.0,4.0,n/e,n/e,...,n/e,n/e,n/e,n/e,n/e,n/e,0.0,73.0,114.0,239.0
4,BZN|DK2,01.01.2020 04:00 - 01.01.2020 05:00 (CET),458.0,n/e,n/e,32.0,184.0,8.0,n/e,n/e,...,n/e,n/e,n/e,n/e,n/e,n/e,0.0,70.0,137.0,254.0

In [7]:
df.dtypes

area                                 object
date_hour                            object
biomass                             float64
fossil_brown_coal_lignite            object
fossil_coal_derived_gas              object
fossil_gas                          float64
fossil_hard_coal                    float64
fossil_oil                          float64
fossil_oil_shale                     object
fossil_peat                          object
geothermal                           object
hydro_pumped_storage                 object
hydro_pumped_storage_consumption     object
hydro_run_river_poundage             object
hydro_water_reservoir                object
marine                               object
nuclear                              object
other                                object
other_renewable                      object
solar                               float64
waste                               float64
wind_offshore                       float64
wind_onshore                        float64
dtype: object

In [13]:
df.shape

(8785, 23)

# Putting the data into the SQLite Database

In [15]:
import sqlite3
conn = sqlite3.connect('production.db') 
c=conn.cursor()

In [16]:
c.execute( 
    """ 
    CREATE TABLE raw_data(
        
                    area TEXT,
                    date_hour TEXT,
                    biomass REAL,
                    fossil_brown_coal_lignite REAL,
                    fossil_coal_derived_gas REAL,
                    fossil_gas REAL,
                    fossil_hard_coal REAL,
                    fossil_oil REAL,
                    fossil_oil_shale REAL,
                    fossil_peat REAL,
                    geothermal REAL,
                    hydro_pumped_storage REAL,
                    hydro_pumped_storage_consumption REAL,
                    hydro_run_river_poundage REAL,
                    hydro_water_reservoir REAL,
                    marine REAL,
                    nuclear REAL,
                    other REAL,
                    other_renewable REAL,
                    solar REAL,
                    waste REAL,
                    wind_offshore REAL,
                    wind_onshore REAL);
"""
)

In [17]:
df.to_sql('raw_data', conn, if_exists='append', index=False) #importing the data into the SQL table

In [18]:
pd.read_sql("SELECT * FROM raw_data LIMIT 5", conn)

,area,date_hour,biomass,fossil_brown_coal_lignite,fossil_coal_derived_gas,fossil_gas,fossil_hard_coal,fossil_oil,fossil_oil_shale,fossil_peat,...,hydro_run_river_poundage,hydro_water_reservoir,marine,nuclear,other,other_renewable,solar,waste,wind_offshore,wind_onshore
0,BZN|DK2,01.01.2020 00:00 - 01.01.2020 01:00 (CET),432.0,n/e,n/e,41.0,198.0,4.0,n/e,n/e,...,n/e,n/e,n/e,n/e,n/e,n/e,0.0,72.0,119.0,255.0
1,BZN|DK2,01.01.2020 01:00 - 01.01.2020 02:00 (CET),460.0,n/e,n/e,41.0,187.0,4.0,n/e,n/e,...,n/e,n/e,n/e,n/e,n/e,n/e,0.0,73.0,105.0,219.0
2,BZN|DK2,01.01.2020 02:00 - 01.01.2020 03:00 (CET),413.0,n/e,n/e,34.0,184.0,4.0,n/e,n/e,...,n/e,n/e,n/e,n/e,n/e,n/e,0.0,72.0,96.0,226.0
3,BZN|DK2,01.01.2020 03:00 - 01.01.2020 04:00 (CET),411.0,n/e,n/e,32.0,180.0,4.0,n/e,n/e,...,n/e,n/e,n/e,n/e,n/e,n/e,0.0,73.0,114.0,239.0
4,BZN|DK2,01.01.2020 04:00 - 01.01.2020 05:00 (CET),458.0,n/e,n/e,32.0,184.0,8.0,n/e,n/e,...,n/e,n/e,n/e,n/e,n/e,n/e,0.0,70.0,137.0,254.0

In [19]:
raw_data.shape

(8785, 23)

In [11]:
conn.close()

#### Raw data has been successfully stored in the SQLite database!